services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - mynet
    restart: unless-stopped

  pgadmin:
    container_name: pgaadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@user.com'
      PGADMIN_DEFAULT_PASSWORD: 'userpassword'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - mynet
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "6060:15672"
      - "5672:5672"
    networks:
      - mynet

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: my-spring-boot-app
    ports:
      - "8080:8080"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  postgres:
  pgadmin: